/// Configuration for [DomainGenerator].
class DomainGeneratorConfig {
  const DomainGeneratorConfig({
    required this.domain,
    required this.entity,
    required this.idType,
    required this.storage,
    required this.sync,
    required this.outputDir,
    this.hiveBox,
    this.driftTable,
    this.sortField,
    this.packageName = 'offline_sync_engine',
  });

  final String domain;
  final String entity;
  final String idType;
  final DomainStorage storage;
  final DomainSync sync;
  final String outputDir;
  final String? hiveBox;
  final String? driftTable;
  final String? sortField;
  final String packageName;

  String get domainPascal => _pascal(domain);
  String get domainSnake => _snake(domain);
  String get entitySnake => _snake(entity);

  /// Public helper for CLI / apps generating entity names from slugs.
  static String slugToPascal(String input) => _pascal(input);

  static String _pascal(String input) {
    return input
        .split(RegExp(r'[_\s-]+'))
        .map((part) =>
            part.isEmpty ? part : part[0].toUpperCase() + part.substring(1))
        .join();
  }

  static String _snake(String input) {
    return input
        .replaceAllMapped(
          RegExp(r'([a-z0-9])([A-Z])'),
          (m) => '${m[1]}_${m[2]}',
        )
        .toLowerCase()
        .replaceAll(RegExp(r'[\s-]+'), '_');
  }

  factory DomainGeneratorConfig.fromYamlMap(Map<dynamic, dynamic> map) {
    return DomainGeneratorConfig(
      domain: map['domain'] as String,
      entity: map['entity'] as String? ?? _pascal(map['domain'] as String),
      idType: map['id_type'] as String? ?? 'String',
      storage: DomainStorage.fromString(map['storage'] as String? ?? 'hive'),
      sync: DomainSync.fromString(map['sync'] as String? ?? 'pull'),
      outputDir: map['output_dir'] as String,
      hiveBox: map['hive_box'] as String?,
      driftTable: map['drift_table'] as String?,
      sortField: map['sort_field'] as String?,
      packageName: map['package_name'] as String? ?? 'offline_sync_engine',
    );
  }
}

enum DomainStorage {
  hive,
  drift,
  memory;

  static DomainStorage fromString(String value) {
    return DomainStorage.values.firstWhere(
      (e) => e.name == value,
      orElse: () => DomainStorage.hive,
    );
  }
}

enum DomainSync {
  pull,
  outbound,
  both;

  static DomainSync fromString(String value) {
    return DomainSync.values.firstWhere(
      (e) => e.name == value,
      orElse: () => DomainSync.pull,
    );
  }
}

/// Writes scaffold files for a new offline domain (list report → list transaction).
class DomainGenerator {
  DomainGenerator(this.config);

  final DomainGeneratorConfig config;

  List<GeneratedFile> generate() {
    final files = <GeneratedFile>[];

    if (config.storage == DomainStorage.hive &&
        (config.sync == DomainSync.pull || config.sync == DomainSync.both)) {
      files.add(_hivePullStore());
    }
    if (config.storage == DomainStorage.hive &&
        (config.sync == DomainSync.outbound || config.sync == DomainSync.both)) {
      files.add(_hiveOutboundStore());
    }
    if (config.storage == DomainStorage.drift &&
        (config.sync == DomainSync.pull || config.sync == DomainSync.both)) {
      files.add(_driftPullAdapter());
    }
    if (config.storage == DomainStorage.drift &&
        (config.sync == DomainSync.outbound || config.sync == DomainSync.both)) {
      files.add(_driftOutboundAdapter());
    }
    if (config.storage == DomainStorage.memory) {
      files.add(_memoryStore());
    }

    files.add(_repository());

    return files;
  }

  GeneratedFile _repository() {
    final c = config;
    final buffer = StringBuffer()
      ..writeln('// GENERATED by offline_sync_engine — safe to edit fetch/push wiring.')
      ..writeln("import 'package:${c.packageName}/${c.packageName}.dart';");

    if (c.storage == DomainStorage.hive) {
      buffer.writeln("import 'package:hive/hive.dart';");
      buffer.writeln("import '${c.domainSnake}_hive_store.dart';");
      if (c.sync == DomainSync.outbound || c.sync == DomainSync.both) {
        buffer.writeln("import '${c.domainSnake}_hive_outbound_store.dart';");
      }
    }
    if (c.storage == DomainStorage.drift) {
      buffer.writeln("import '${c.domainSnake}_drift_adapter.dart';");
      if (c.sync == DomainSync.outbound || c.sync == DomainSync.both) {
        buffer.writeln("import '${c.domainSnake}_drift_outbound_adapter.dart';");
      }
    }
    if (c.storage == DomainStorage.memory) {
      buffer.writeln("import '${c.domainSnake}_memory_store.dart';");
    }

    buffer.writeln();
    buffer.writeln('/// Offline-first repository for ${c.entity}.');
    buffer.writeln('class ${c.domainPascal}Repository {');

    if (c.sync == DomainSync.pull || c.sync == DomainSync.both) {
      buffer.writeln('  ${c.domainPascal}Repository.pull({');
      if (c.storage == DomainStorage.hive) {
        buffer.writeln('    required Box<${c.entity}> box,');
      }
      if (c.storage == DomainStorage.drift) {
        buffer.writeln('    required ${c.domainPascal}DriftCacheAdapter adapter,');
      }
      buffer.writeln('    required Future<List<${c.entity}>> Function() fetchAll,');
      buffer.writeln('    required Future<bool> Function() isOnline,');
      buffer.writeln('  }) : _pull = PullCacheRepository<${c.entity}, ${c.idType}>(');
      _writePullStoreInit(buffer);
      buffer.writeln('          fetchAll: fetchAll,');
      buffer.writeln('          isOnline: isOnline,');
      buffer.writeln('        );');
    }

    if (c.sync == DomainSync.outbound || c.sync == DomainSync.both) {
      buffer.writeln('  ${c.domainPascal}Repository.outbound({');
      if (c.storage == DomainStorage.hive) {
        buffer.writeln('    required Box<${c.entity}> box,');
      }
      if (c.storage == DomainStorage.drift) {
        buffer.writeln('    required ${c.domainPascal}DriftOutboundAdapter adapter,');
      }
      buffer.writeln('    required Future<SyncOutcome> Function(${c.entity} item) pushOne,');
      buffer.writeln('    required Future<bool> Function() isOnline,');
      buffer.writeln('    required OutboundItemStatus Function(${c.entity} item) statusOf,');
      buffer.writeln('    required ${c.entity} Function(${c.entity} item, OutboundItemStatus status, {String? errorMessage}) withStatus,');
      if (c.storage == DomainStorage.memory) {
        buffer.writeln('  })  : memoryBundle = ${c.domainPascal}MemoryBundle(');
        buffer.writeln('          statusOf: statusOf,');
        buffer.writeln('          withStatus: withStatus,');
        buffer.writeln('        ),');
        buffer.writeln('        _outbound = OutboundRepository<${c.entity}, ${c.idType}>(');
      } else {
        buffer.writeln('  }) : _outbound = OutboundRepository<${c.entity}, ${c.idType}>(');
      }
      _writeOutboundStoreInit(buffer);
      buffer.writeln('          pushOne: pushOne,');
      buffer.writeln('          isOnline: isOnline,');
      buffer.writeln('          statusOf: statusOf,');
      buffer.writeln('          withStatus: withStatus,');
      buffer.writeln('        );');
    }

    if (c.sync == DomainSync.both) {
      buffer.writeln('  ${c.domainPascal}Repository.both({');
      if (c.storage == DomainStorage.hive) {
        buffer.writeln('    required Box<${c.entity}> box,');
      }
      if (c.storage == DomainStorage.drift) {
        buffer.writeln('    required ${c.domainPascal}DriftCacheAdapter pullAdapter,');
        buffer.writeln('    required ${c.domainPascal}DriftOutboundAdapter outboundAdapter,');
      }
      buffer.writeln('    required Future<List<${c.entity}>> Function() fetchAll,');
      buffer.writeln('    required Future<SyncOutcome> Function(${c.entity} item) pushOne,');
      buffer.writeln('    required Future<bool> Function() isOnline,');
      buffer.writeln('    required OutboundItemStatus Function(${c.entity} item) statusOf,');
      buffer.writeln('    required ${c.entity} Function(${c.entity} item, OutboundItemStatus status, {String? errorMessage}) withStatus,');
      if (c.storage == DomainStorage.memory) {
        buffer.writeln('  })  : memoryBundle = ${c.domainPascal}MemoryBundle(');
        buffer.writeln('          statusOf: statusOf,');
        buffer.writeln('          withStatus: withStatus,');
        buffer.writeln('        ),');
        buffer.writeln('        _pull = PullCacheRepository<${c.entity}, ${c.idType}>(');
        _writePullStoreInit(buffer, memoryVar: 'memoryBundle.store');
        buffer.writeln('          fetchAll: fetchAll,');
        buffer.writeln('          isOnline: isOnline,');
        buffer.writeln('        ),');
        buffer.writeln('        _outbound = OutboundRepository<${c.entity}, ${c.idType}>(');
        _writeOutboundStoreInit(buffer, memoryVar: 'memoryBundle');
        buffer.writeln('          pushOne: pushOne,');
        buffer.writeln('          isOnline: isOnline,');
        buffer.writeln('          statusOf: statusOf,');
        buffer.writeln('          withStatus: withStatus,');
        buffer.writeln('        );');
      } else {
        buffer.writeln('  })  : _pull = PullCacheRepository<${c.entity}, ${c.idType}>(');
        _writePullStoreInit(buffer, driftVar: 'pullAdapter');
        buffer.writeln('          fetchAll: fetchAll,');
        buffer.writeln('          isOnline: isOnline,');
        buffer.writeln('        ),');
        buffer.writeln('        _outbound = OutboundRepository<${c.entity}, ${c.idType}>(');
        _writeOutboundStoreInit(buffer, driftVar: 'outboundAdapter');
        buffer.writeln('          pushOne: pushOne,');
        buffer.writeln('          isOnline: isOnline,');
        buffer.writeln('          statusOf: statusOf,');
        buffer.writeln('          withStatus: withStatus,');
        buffer.writeln('        );');
      }
    }

    if (c.storage == DomainStorage.memory &&
        (c.sync == DomainSync.outbound || c.sync == DomainSync.both)) {
      buffer.writeln('  final ${c.domainPascal}MemoryBundle memoryBundle;');
    }

    if (c.sync == DomainSync.pull || c.sync == DomainSync.both) {
      buffer.writeln('  final PullCacheRepository<${c.entity}, ${c.idType}>? _pull;');
      buffer.writeln('  PullCacheRepository<${c.entity}, ${c.idType}> get pull => _pull!;');
      buffer.writeln('  Stream<CacheSnapshot<${c.entity}>> watchSnapshot() => pull.watchSnapshot();');
      buffer.writeln('  Future<CacheLoadResult<${c.entity}>> load({bool refreshIfOnline = true}) => pull.load(refreshIfOnline: refreshIfOnline);');
      buffer.writeln('  Future<void> refresh() => pull.refresh();');
    }

    if (c.sync == DomainSync.outbound || c.sync == DomainSync.both) {
      buffer.writeln('  final OutboundRepository<${c.entity}, ${c.idType}>? _outbound;');
      buffer.writeln('  OutboundRepository<${c.entity}, ${c.idType}> get outbound => _outbound!;');
      buffer.writeln('  SyncPass<${c.entity}, ${c.idType}> get syncPass => outbound.syncPass;');
      buffer.writeln('  Stream<List<${c.entity}>> watchAll() => outbound.watchAll();');
      buffer.writeln('  Future<void> save(${c.entity} item, {bool syncIfOnline = true}) => outbound.save(item, syncIfOnline: syncIfOnline);');
    }

    buffer.writeln('}');

    return GeneratedFile(
      path: '${c.outputDir}/${c.domainSnake}_repository.dart',
      content: buffer.toString(),
    );
  }

  void _writePullStoreInit(
    StringBuffer buffer, {
    String driftVar = 'adapter',
    String? memoryVar,
  }) {
    final c = config;
    buffer.writeln('          store: ');
    switch (c.storage) {
      case DomainStorage.hive:
        buffer.writeln('              ${c.domainPascal}HiveLocalStore(box: box),');
      case DomainStorage.drift:
        buffer.writeln('              DriftLocalDataStore($driftVar),');
      case DomainStorage.memory:
        buffer.writeln(
          '              ${memoryVar ?? '${c.domainPascal}MemoryStore()'},',
        );
    }
  }

  void _writeOutboundStoreInit(
    StringBuffer buffer, {
    String driftVar = 'adapter',
    String memoryVar = 'memoryBundle',
  }) {
    final c = config;
    buffer.writeln('          readStore: ');
    switch (c.storage) {
      case DomainStorage.hive:
        buffer.writeln('              ${c.domainPascal}HiveLocalStore(box: box),');
        buffer.writeln('          queueStore: ${c.domainPascal}HiveOutboundQueueStore(');
        buffer.writeln('            box: box,');
        buffer.writeln('            statusOf: statusOf,');
        buffer.writeln('            withStatus: withStatus,');
        buffer.writeln('          ),');
      case DomainStorage.drift:
        buffer.writeln('              DriftLocalDataStore($driftVar),');
        buffer.writeln('          queueStore: DriftOutboundQueueStore($driftVar),');
      case DomainStorage.memory:
        buffer.writeln('              $memoryVar.store,');
        buffer.writeln('          queueStore: $memoryVar.queueStore,');
    }
  }

  GeneratedFile _hivePullStore() {
    final c = config;
    final box = c.hiveBox ?? c.domainSnake;
    final sort = c.sortField != null
        ? 'sort: (a, b) => a.${c.sortField}.compareTo(b.${c.sortField}),'
        : '';

    return GeneratedFile(
      path: '${c.outputDir}/${c.domainSnake}_hive_store.dart',
      content: '''
import 'package:hive/hive.dart';
import 'package:${c.packageName}/${c.packageName}.dart';

/// Hive local store for ${c.entity}. Uses \`id\` as the box key.
class ${c.domainPascal}HiveLocalStore extends HiveLocalDataStore<${c.entity}, ${c.idType}> {
  ${c.domainPascal}HiveLocalStore({required Box<${c.entity}> box})
      : super(
          box: box,
          idOf: (item) => item.id,
          $sort
        );
}
''',
    );
  }

  GeneratedFile _hiveOutboundStore() {
    final c = config;
    return GeneratedFile(
      path: '${c.outputDir}/${c.domainSnake}_hive_outbound_store.dart',
      content: '''
import 'package:hive/hive.dart';
import 'package:${c.packageName}/${c.packageName}.dart';

class ${c.domainPascal}HiveOutboundQueueStore extends HiveOutboundQueueStore<${c.entity}, ${c.idType}> {
  ${c.domainPascal}HiveOutboundQueueStore({
    required Box<${c.entity}> box,
    required super.statusOf,
    required super.withStatus,
  }) : super(box: box, idOf: (item) => item.id);
}
''',
    );
  }

  GeneratedFile _driftPullAdapter() {
    final c = config;
    final table = c.driftTable ?? '${c.domainPascal}s';
    return GeneratedFile(
      path: '${c.outputDir}/${c.domainSnake}_drift_adapter.dart',
      content: '''
import 'package:${c.packageName}/${c.packageName}.dart';

// import your generated database + entity here:
// import 'package:my_app/database/app_database.dart';

/// Implement DAO calls against your Drift $table table.
class ${c.domainPascal}DriftCacheAdapter implements DriftCacheAdapter<${c.entity}, ${c.idType}> {
  // ${c.domainPascal}DriftCacheAdapter(this._db);
  // final AppDatabase _db;

  @override
  Future<List<${c.entity}>> getAll() {
    throw UnimplementedError('Wire to _db.${c.domainSnake}Dao.getAll()');
  }

  @override
  Future<${c.entity}?> getById(${c.idType} id) {
    throw UnimplementedError('Wire to _db.${c.domainSnake}Dao.getById(id)');
  }

  @override
  Future<void> replaceAll(List<${c.entity}> items) {
    throw UnimplementedError('Wire to _db.${c.domainSnake}Dao.replaceAll(items)');
  }

  @override
  Future<void> upsert(${c.entity} item) {
    throw UnimplementedError('Wire to _db.${c.domainSnake}Dao.upsert(item)');
  }

  @override
  Future<void> deleteById(${c.idType} id) {
    throw UnimplementedError('Wire to _db.${c.domainSnake}Dao.deleteById(id)');
  }

  @override
  ${c.idType} idOf(${c.entity} item) => item.id;

  @override
  Stream<void> watchChanges() {
    throw UnimplementedError('Wire to _db.${c.domainSnake}Dao.watchAll().map((_) {})');
  }
}
''',
    );
  }

  GeneratedFile _driftOutboundAdapter() {
    final c = config;
    return GeneratedFile(
      path: '${c.outputDir}/${c.domainSnake}_drift_outbound_adapter.dart',
      content: '''
import 'package:${c.packageName}/${c.packageName}.dart';

class ${c.domainPascal}DriftOutboundAdapter implements DriftOutboundAdapter<${c.entity}, ${c.idType}> {
  @override
  Future<List<${c.entity}>> getAll() => throw UnimplementedError();

  @override
  Future<${c.entity}?> getById(${c.idType} id) => throw UnimplementedError();

  @override
  Future<void> deleteById(${c.idType} id) => throw UnimplementedError();

  @override
  Future<void> save(${c.entity} item) => throw UnimplementedError();

  @override
  ${c.idType} idOf(${c.entity} item) => item.id;

  @override
  OutboundItemStatus statusOf(${c.entity} item) => throw UnimplementedError();

  @override
  ${c.entity} withStatus(${c.entity} item, OutboundItemStatus status, {String? errorMessage}) =>
      throw UnimplementedError();
}
''',
    );
  }

  GeneratedFile _memoryStore() {
    final c = config;
    final sort = c.sortField != null
        ? 'sort: (a, b) => a.${c.sortField}.compareTo(b.${c.sortField}),'
        : '';
    return GeneratedFile(
      path: '${c.outputDir}/${c.domainSnake}_memory_store.dart',
      content: '''
import 'package:${c.packageName}/${c.packageName}.dart';

class ${c.domainPascal}MemoryStore extends MemoryLocalDataStore<${c.entity}, ${c.idType}> {
  ${c.domainPascal}MemoryStore()
      : super(idOf: (item) => item.id, $sort);
}

class ${c.domainPascal}MemoryBundle {
  ${c.domainPascal}MemoryBundle._({
    required this.store,
    required this.queueStore,
    required this.statusOf,
    required this.withStatus,
  });

  factory ${c.domainPascal}MemoryBundle({
    required OutboundItemStatus Function(${c.entity} item) statusOf,
    required ${c.entity} Function(${c.entity} item, OutboundItemStatus status, {String? errorMessage}) withStatus,
  }) {
    final store = ${c.domainPascal}MemoryStore();
    return ${c.domainPascal}MemoryBundle._(
      store: store,
      queueStore: ${c.domainPascal}MemoryOutboundQueueStore(
        store: store,
        statusOf: statusOf,
        withStatus: withStatus,
      ),
      statusOf: statusOf,
      withStatus: withStatus,
    );
  }

  final ${c.domainPascal}MemoryStore store;
  final ${c.domainPascal}MemoryOutboundQueueStore queueStore;
  final OutboundItemStatus Function(${c.entity} item) statusOf;
  final ${c.entity} Function(${c.entity} item, OutboundItemStatus status, {String? errorMessage}) withStatus;
}

class ${c.domainPascal}MemoryOutboundQueueStore implements OfflineQueueStore<${c.entity}, ${c.idType}> {
  ${c.domainPascal}MemoryOutboundQueueStore({
    required MemoryLocalDataStore<${c.entity}, ${c.idType}> store,
    required this.statusOf,
    required this.withStatus,
  }) : _store = store;

  final MemoryLocalDataStore<${c.entity}, ${c.idType}> _store;
  final OutboundItemStatus Function(${c.entity} item) statusOf;
  final ${c.entity} Function(${c.entity} item, OutboundItemStatus status, {String? errorMessage}) withStatus;

  @override
  Future<List<${c.entity}>> getPending() async {
    final all = await _store.getAll();
    return all.where((e) => statusOf(e) == OutboundItemStatus.pending).toList();
  }

  @override
  Future<void> remove(${c.idType} id) => _store.deleteById(id);

  @override
  Future<${c.entity}?> getById(${c.idType} id) => _store.getById(id);

  @override
  Future<void> markFailed(${c.idType} id, {String? errorMessage}) async {
    final existing = await _store.getById(id);
    if (existing == null) return;
    await _store.upsert(withStatus(existing, OutboundItemStatus.failed, errorMessage: errorMessage));
  }

  @override
  ${c.idType} idOf(${c.entity} item) => _store.idOf(item);
}
''',
    );
  }
}

class GeneratedFile {
  const GeneratedFile({required this.path, required this.content});
  final String path;
  final String content;
}
